package com.excel.dataobject;

import java.util.Date;

public class DataProcessDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_process.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_process.data_process_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String dataProcessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_process.data_process_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String dataProcessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_process.rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String rule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_process.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_process.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_process.id
     *
     * @return the value of data_process.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_process.id
     *
     * @param id the value for data_process.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_process.data_process_name
     *
     * @return the value of data_process.data_process_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getDataProcessName() {
        return dataProcessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_process.data_process_name
     *
     * @param dataProcessName the value for data_process.data_process_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setDataProcessName(String dataProcessName) {
        this.dataProcessName = dataProcessName == null ? null : dataProcessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_process.data_process_type
     *
     * @return the value of data_process.data_process_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getDataProcessType() {
        return dataProcessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_process.data_process_type
     *
     * @param dataProcessType the value for data_process.data_process_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setDataProcessType(String dataProcessType) {
        this.dataProcessType = dataProcessType == null ? null : dataProcessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_process.rule
     *
     * @return the value of data_process.rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_process.rule
     *
     * @param rule the value for data_process.rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_process.create_time
     *
     * @return the value of data_process.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_process.create_time
     *
     * @param createTime the value for data_process.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_process.update_time
     *
     * @return the value of data_process.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_process.update_time
     *
     * @param updateTime the value for data_process.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}