package com.excel.dataobject;

import java.util.Date;

public class DataFilterProcessDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_filter_process.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_filter_process.data_filter_process_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String dataFilterProcessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_filter_process.create_user_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_filter_process.rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String rule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_filter_process.threshold
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String threshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_filter_process.threshold_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String thresholdType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_filter_process.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_filter_process.id
     *
     * @return the value of data_filter_process.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_filter_process.id
     *
     * @param id the value for data_filter_process.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_filter_process.data_filter_process_name
     *
     * @return the value of data_filter_process.data_filter_process_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getDataFilterProcessName() {
        return dataFilterProcessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_filter_process.data_filter_process_name
     *
     * @param dataFilterProcessName the value for data_filter_process.data_filter_process_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setDataFilterProcessName(String dataFilterProcessName) {
        this.dataFilterProcessName = dataFilterProcessName == null ? null : dataFilterProcessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_filter_process.create_user_id
     *
     * @return the value of data_filter_process.create_user_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_filter_process.create_user_id
     *
     * @param createUserId the value for data_filter_process.create_user_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_filter_process.rule
     *
     * @return the value of data_filter_process.rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_filter_process.rule
     *
     * @param rule the value for data_filter_process.rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_filter_process.threshold
     *
     * @return the value of data_filter_process.threshold
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_filter_process.threshold
     *
     * @param threshold the value for data_filter_process.threshold
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setThreshold(String threshold) {
        this.threshold = threshold == null ? null : threshold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_filter_process.threshold_type
     *
     * @return the value of data_filter_process.threshold_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getThresholdType() {
        return thresholdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_filter_process.threshold_type
     *
     * @param thresholdType the value for data_filter_process.threshold_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setThresholdType(String thresholdType) {
        this.thresholdType = thresholdType == null ? null : thresholdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_filter_process.create_time
     *
     * @return the value of data_filter_process.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_filter_process.create_time
     *
     * @param createTime the value for data_filter_process.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}