package com.excel.dataobject;

import java.util.Date;

public class GeoBankDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_bank.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_bank.name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_bank.bank_geo_detail
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String bankGeoDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_bank.geo_level
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String geoLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_bank.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_bank.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_bank.id
     *
     * @return the value of geo_bank.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_bank.id
     *
     * @param id the value for geo_bank.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_bank.name
     *
     * @return the value of geo_bank.name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_bank.name
     *
     * @param name the value for geo_bank.name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_bank.bank_geo_detail
     *
     * @return the value of geo_bank.bank_geo_detail
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getBankGeoDetail() {
        return bankGeoDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_bank.bank_geo_detail
     *
     * @param bankGeoDetail the value for geo_bank.bank_geo_detail
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setBankGeoDetail(String bankGeoDetail) {
        this.bankGeoDetail = bankGeoDetail == null ? null : bankGeoDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_bank.geo_level
     *
     * @return the value of geo_bank.geo_level
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getGeoLevel() {
        return geoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_bank.geo_level
     *
     * @param geoLevel the value for geo_bank.geo_level
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setGeoLevel(String geoLevel) {
        this.geoLevel = geoLevel == null ? null : geoLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_bank.create_time
     *
     * @return the value of geo_bank.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_bank.create_time
     *
     * @param createTime the value for geo_bank.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_bank.update_time
     *
     * @return the value of geo_bank.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_bank.update_time
     *
     * @param updateTime the value for geo_bank.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}