package com.excel.dataobject;

import java.util.Date;

public class IndexSheetDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_sheet.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_sheet.index_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer indexId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_sheet.index_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String indexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_sheet.show_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String showName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_sheet.sort_rule_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer sortRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_sheet.data_process_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer dataProcessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_sheet.sheet_format_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer sheetFormatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_sheet.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_sheet.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_sheet.id
     *
     * @return the value of index_sheet.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_sheet.id
     *
     * @param id the value for index_sheet.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_sheet.index_id
     *
     * @return the value of index_sheet.index_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_sheet.index_id
     *
     * @param indexId the value for index_sheet.index_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_sheet.index_name
     *
     * @return the value of index_sheet.index_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_sheet.index_name
     *
     * @param indexName the value for index_sheet.index_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_sheet.show_name
     *
     * @return the value of index_sheet.show_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_sheet.show_name
     *
     * @param showName the value for index_sheet.show_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_sheet.sort_rule_id
     *
     * @return the value of index_sheet.sort_rule_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getSortRuleId() {
        return sortRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_sheet.sort_rule_id
     *
     * @param sortRuleId the value for index_sheet.sort_rule_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setSortRuleId(Integer sortRuleId) {
        this.sortRuleId = sortRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_sheet.data_process_id
     *
     * @return the value of index_sheet.data_process_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getDataProcessId() {
        return dataProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_sheet.data_process_id
     *
     * @param dataProcessId the value for index_sheet.data_process_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setDataProcessId(Integer dataProcessId) {
        this.dataProcessId = dataProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_sheet.sheet_format_id
     *
     * @return the value of index_sheet.sheet_format_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getSheetFormatId() {
        return sheetFormatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_sheet.sheet_format_id
     *
     * @param sheetFormatId the value for index_sheet.sheet_format_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setSheetFormatId(Integer sheetFormatId) {
        this.sheetFormatId = sheetFormatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_sheet.create_time
     *
     * @return the value of index_sheet.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_sheet.create_time
     *
     * @param createTime the value for index_sheet.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_sheet.update_time
     *
     * @return the value of index_sheet.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_sheet.update_time
     *
     * @param updateTime the value for index_sheet.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}