package com.excel.dataobject;

import java.util.Date;

public class IndexInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.dim
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String dim;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.data_base
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String dataBase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.table
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String table;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.field
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String field;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.field_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String fieldType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.id
     *
     * @return the value of index_info.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.id
     *
     * @param id the value for index_info.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.dim
     *
     * @return the value of index_info.dim
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getDim() {
        return dim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.dim
     *
     * @param dim the value for index_info.dim
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setDim(String dim) {
        this.dim = dim == null ? null : dim.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.name
     *
     * @return the value of index_info.name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.name
     *
     * @param name the value for index_info.name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.data_base
     *
     * @return the value of index_info.data_base
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getDataBase() {
        return dataBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.data_base
     *
     * @param dataBase the value for index_info.data_base
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setDataBase(String dataBase) {
        this.dataBase = dataBase == null ? null : dataBase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.table
     *
     * @return the value of index_info.table
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.table
     *
     * @param table the value for index_info.table
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setTable(String table) {
        this.table = table == null ? null : table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.field
     *
     * @return the value of index_info.field
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.field
     *
     * @param field the value for index_info.field
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.create_time
     *
     * @return the value of index_info.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.create_time
     *
     * @param createTime the value for index_info.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.update_time
     *
     * @return the value of index_info.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.update_time
     *
     * @param updateTime the value for index_info.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.field_type
     *
     * @return the value of index_info.field_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.field_type
     *
     * @param fieldType the value for index_info.field_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType == null ? null : fieldType.trim();
    }
}