package com.excel.dataobject;

import java.util.Date;

public class SheetModelDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet_model.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet_model.sheet_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String sheetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet_model.data_base
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String dataBase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet_model.table
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String table;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet_model.create_user_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet_model.index_sheet_list
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String indexSheetList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet_model.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet_model.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet_model.id
     *
     * @return the value of sheet_model.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet_model.id
     *
     * @param id the value for sheet_model.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet_model.sheet_name
     *
     * @return the value of sheet_model.sheet_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getSheetName() {
        return sheetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet_model.sheet_name
     *
     * @param sheetName the value for sheet_model.sheet_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setSheetName(String sheetName) {
        this.sheetName = sheetName == null ? null : sheetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet_model.data_base
     *
     * @return the value of sheet_model.data_base
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getDataBase() {
        return dataBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet_model.data_base
     *
     * @param dataBase the value for sheet_model.data_base
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setDataBase(String dataBase) {
        this.dataBase = dataBase == null ? null : dataBase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet_model.table
     *
     * @return the value of sheet_model.table
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet_model.table
     *
     * @param table the value for sheet_model.table
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setTable(String table) {
        this.table = table == null ? null : table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet_model.create_user_id
     *
     * @return the value of sheet_model.create_user_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet_model.create_user_id
     *
     * @param createUserId the value for sheet_model.create_user_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet_model.index_sheet_list
     *
     * @return the value of sheet_model.index_sheet_list
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getIndexSheetList() {
        return indexSheetList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet_model.index_sheet_list
     *
     * @param indexSheetList the value for sheet_model.index_sheet_list
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setIndexSheetList(String indexSheetList) {
        this.indexSheetList = indexSheetList == null ? null : indexSheetList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet_model.create_time
     *
     * @return the value of sheet_model.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet_model.create_time
     *
     * @param createTime the value for sheet_model.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet_model.update_time
     *
     * @return the value of sheet_model.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet_model.update_time
     *
     * @param updateTime the value for sheet_model.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}