package com.excel.dataobject;

import java.util.Date;

public class SortRuleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_rule.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_rule.index_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer indexId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_rule.rule_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String ruleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_rule.sort_level
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String sortLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_rule.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_rule.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_rule.rule_num
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String ruleNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_rule.id
     *
     * @return the value of sort_rule.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_rule.id
     *
     * @param id the value for sort_rule.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_rule.index_id
     *
     * @return the value of sort_rule.index_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_rule.index_id
     *
     * @param indexId the value for sort_rule.index_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_rule.rule_type
     *
     * @return the value of sort_rule.rule_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_rule.rule_type
     *
     * @param ruleType the value for sort_rule.rule_type
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType == null ? null : ruleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_rule.sort_level
     *
     * @return the value of sort_rule.sort_level
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getSortLevel() {
        return sortLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_rule.sort_level
     *
     * @param sortLevel the value for sort_rule.sort_level
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setSortLevel(String sortLevel) {
        this.sortLevel = sortLevel == null ? null : sortLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_rule.create_time
     *
     * @return the value of sort_rule.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_rule.create_time
     *
     * @param createTime the value for sort_rule.create_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_rule.update_time
     *
     * @return the value of sort_rule.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_rule.update_time
     *
     * @param updateTime the value for sort_rule.update_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_rule.rule_num
     *
     * @return the value of sort_rule.rule_num
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getRuleNum() {
        return ruleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_rule.rule_num
     *
     * @param ruleNum the value for sort_rule.rule_num
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setRuleNum(String ruleNum) {
        this.ruleNum = ruleNum == null ? null : ruleNum.trim();
    }
}