package com.excel.dataobject;

public class UploadFileTaskDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.user_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.excel_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String excelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.excel_model_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer excelModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.file_saved_path
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String fileSavedPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.state
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.error_code
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String errorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.begin_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.end_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file_task.file_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.id
     *
     * @return the value of upload_file_task.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.id
     *
     * @param id the value for upload_file_task.id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.user_id
     *
     * @return the value of upload_file_task.user_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.user_id
     *
     * @param userId the value for upload_file_task.user_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.excel_name
     *
     * @return the value of upload_file_task.excel_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getExcelName() {
        return excelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.excel_name
     *
     * @param excelName the value for upload_file_task.excel_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setExcelName(String excelName) {
        this.excelName = excelName == null ? null : excelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.excel_model_id
     *
     * @return the value of upload_file_task.excel_model_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getExcelModelId() {
        return excelModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.excel_model_id
     *
     * @param excelModelId the value for upload_file_task.excel_model_id
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setExcelModelId(Integer excelModelId) {
        this.excelModelId = excelModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.file_saved_path
     *
     * @return the value of upload_file_task.file_saved_path
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getFileSavedPath() {
        return fileSavedPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.file_saved_path
     *
     * @param fileSavedPath the value for upload_file_task.file_saved_path
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setFileSavedPath(String fileSavedPath) {
        this.fileSavedPath = fileSavedPath == null ? null : fileSavedPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.state
     *
     * @return the value of upload_file_task.state
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.state
     *
     * @param state the value for upload_file_task.state
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.error_code
     *
     * @return the value of upload_file_task.error_code
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.error_code
     *
     * @param errorCode the value for upload_file_task.error_code
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.begin_time
     *
     * @return the value of upload_file_task.begin_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.begin_time
     *
     * @param beginTime the value for upload_file_task.begin_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime == null ? null : beginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.end_time
     *
     * @return the value of upload_file_task.end_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.end_time
     *
     * @param endTime the value for upload_file_task.end_time
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file_task.file_name
     *
     * @return the value of upload_file_task.file_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file_task.file_name
     *
     * @param fileName the value for upload_file_task.file_name
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}