package com.excel.dao;

import com.excel.dataobject.DataProcessDO;

public interface DataProcessDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insert(DataProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insertSelective(DataProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    DataProcessDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKeySelective(DataProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKey(DataProcessDO record);
}