package com.excel.dao;

import com.excel.dataobject.DataFilterProcessDO;

public interface DataFilterProcessDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_filter_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_filter_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insert(DataFilterProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_filter_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insertSelective(DataFilterProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_filter_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    DataFilterProcessDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_filter_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKeySelective(DataFilterProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_filter_process
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKey(DataFilterProcessDO record);
}