package com.excel.dao;

import com.excel.dataobject.GeoBankDO;

public interface GeoBankDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_bank
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_bank
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insert(GeoBankDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_bank
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insertSelective(GeoBankDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_bank
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    GeoBankDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_bank
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKeySelective(GeoBankDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_bank
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKey(GeoBankDO record);
}