package com.excel.dao;

import com.excel.dataobject.IndexInfoDO;

public interface IndexInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_info
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_info
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insert(IndexInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_info
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insertSelective(IndexInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_info
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    IndexInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_info
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKeySelective(IndexInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_info
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKey(IndexInfoDO record);
}