package com.excel.dao;

import com.excel.dataobject.SheetFormatDO;

public interface SheetFormatDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_format
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_format
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insert(SheetFormatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_format
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insertSelective(SheetFormatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_format
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    SheetFormatDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_format
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKeySelective(SheetFormatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_format
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKey(SheetFormatDO record);
}