package com.excel.dao;

import com.excel.dataobject.SheetModelDO;

public interface SheetModelDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_model
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_model
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insert(SheetModelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_model
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insertSelective(SheetModelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_model
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    SheetModelDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_model
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKeySelective(SheetModelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_model
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKey(SheetModelDO record);
}