package com.excel.dao;

import com.excel.dataobject.SortRuleDO;

public interface SortRuleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort_rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort_rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insert(SortRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort_rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insertSelective(SortRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort_rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    SortRuleDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort_rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKeySelective(SortRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort_rule
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKey(SortRuleDO record);
}