package com.excel.dao;

import com.excel.dataobject.UploadFileTaskDO;

public interface UploadFileTaskDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file_task
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file_task
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insert(UploadFileTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file_task
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insertSelective(UploadFileTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file_task
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    UploadFileTaskDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file_task
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKeySelective(UploadFileTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file_task
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int updateByPrimaryKey(UploadFileTaskDO record);
}