package com.excel.dao;

import com.excel.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Dec 25 22:34:35 CST 2024
     */
    int insertSelective(UserDO record);
}